/*function resolveAfter2Seconds() {
    return new Promise(resolve => {
      setTimeout(() => {
        resolve('resolved');
      }, 2000);
    });
  }
  
  async function asyncCall() {
    console.log('calling');
    const result = await resolveAfter2Seconds();
    console.log(result);
    // expected output: "resolved"
  }
  
  asyncCall();*/
  
let double = (a) => a * 2;
    setTimeout(function () {
        console.log( double(10) );
    },2000);

async function Async() {
    try {
     console.log('calling');
      let message = await double();
      console.log(message);
    } catch (error) {
      console.log("Error: " + error);
    }
  }
 
  Async();
